from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse

import uvicorn
from pydantic import BaseModel
from master_router import app as master_swarm # Assuming 'app' is your compiled graph

# Phase A: The Server Scaffold
app = FastAPI(title="Chimera Swarm API", description="Multi-Agent Academic Router")

# Phase B: Request & Response Guardrails
class SwarmRequest(BaseModel):
    prompt: str
    thread_id: str

class SwarmResponse(BaseModel):
    final_response: str
    status: str

# Phase C: The Graph Endpoint & Checkpointer
@app.post("/api/chat", response_model=SwarmResponse)
async def chat_endpoint(request: SwarmRequest):
    config = {"configurable": {"thread_id": request.thread_id}}
    
    try:
        # 1. Execute the Swarm
        final_state = await master_swarm.ainvoke({"messages": [("user", request.prompt)]}, config=config)
        
        # 2. Extract the actual text string from the AIMessage object
        last_message = final_state["messages"][-1]
        response_text = last_message.content 
        
        # 3. Return the clean string to Pydantic
        return SwarmResponse(final_response=response_text, status="success")
        
    except Exception as e:
        # Always catch errors in production APIs
        return SwarmResponse(final_response=f"Swarm Error: {str(e)}", status="error")
@app.post("/api/chat/stream")
async def stream_chat_endpoint(request: SwarmRequest):
    """Streaming endpoint that yields tokens as they're generated by the graph."""
    
    # Define a nested async generator function
    async def event_generator(prompt: str, thread_id: str):
        """
        Async generator that yields tokens from the LangGraph model stream.
        Yields individual tokens as they arrive from the AI model.
        """
        config = {"configurable": {"thread_id": thread_id}}
        
        try:
            # Stream events from the LangGraph asynchronously
            async for event in master_swarm.astream_events(
                {"messages": [("user", prompt)]}, 
                version="v2", 
                config=config
            ):
                # Check if this event is a chat model stream event
                if event["event"] == "on_chat_model_stream":
                    # Extract the token content from the event data
                    token = event["data"]["chunk"].content
                    
                    # Only yield non-empty tokens
                    if token:
                        yield token
                        
        except Exception as e:
            yield f"Error during streaming: {str(e)}"
    
    # Return the async generator wrapped in StreamingResponse
    return StreamingResponse(
        event_generator(request.prompt, request.thread_id), 
        media_type="text/event-stream"
    )


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)